worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout 65;
    client_max_body_size 10M;

    proxy_set_header X-Forwarded-For   $http_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
    proxy_set_header X-Real-IP         $http_x_real_ip;
    proxy_read_timeout 60s;

    upstream backend  { server backend:8080;  }
    upstream frontend { server frontend:3000; }

    # api.pumpking.club → Spring Boot
    server {
        listen 80;
        server_name api.pumpking.club;

        location / {
            proxy_set_header Host $host;
            proxy_pass http://backend;
        }
    }

    # pumpking.club + *.pumpking.club + custom domeny Pro
    server {
        listen 80 default_server;
        server_name _;

        location /api/files/images/ {
            alias /uploads/products/;
            expires 7d;
            add_header Cache-Control "public, immutable";
        }

        location / {
            proxy_set_header Host $host;
            proxy_pass http://frontend;
        }
    }
}
